apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculadora-deployment
  labels:
    app: calculadora
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calculadora
  template:
    metadata:
      labels:
        app: calculadora
    spec:
      containers:
        - name: calculadora
          image: saranda06/calculadora-nube:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000