apiVersion: v1
kind: Service
metadata:
  name: calculadora-service
  labels:
    app: calculadora
spec:
  type: NodePort
  selector:
    app: calculadora
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080